### ISSUE TITLE
Allow change theme easily

### ISSUE THREAD

**Issue by Jeconias** [Jeconias/calendarjs#27]
Allow change theme using method. I believe this is useful.

**Comment by asaki444** [comment]
do you need a button on the app to change the theme as well?

**Comment by Jeconias** [comment]
> do you need a button on the app to change the theme as well?

Not exactly, but this is interesting.  Perhaps the button should be displayed if the developer enters a true state.

**Comment by leventdeniz** [comment]
@Jeconias Maybe you want to add a little settings wheel, that only appears if the state is true? You could add more settings if you'd want in the future there which could be saved to the local storage.

**Comment by Jeconias** [comment]
> @Jeconias Maybe you want to add a little settings wheel, that only appears if the state is true? You could add more settings if you'd want in the future there which could be saved to the local storage.

This is good ideia and will allow more customization. thx! :grin:
