### ISSUE TITLE
Translate README file to English

### ISSUE THREAD

**Issue by Jeconias** [Jeconias/calendarjs#3]

**Comment by NeonNature** [comment]
May I know if translating involves the texts for screenshots too?

**Comment by Jeconias** [comment]
> May I know if translating involves the texts for screenshots too?

Yes, the whole project should be translated.

**Comment by shrangi** [comment]
I'm also working on this issue :)

**Comment by NeonNature** [comment]
> > May I know if translating involves the texts for screenshots too?
> 
> Yes, the whole project should be translated.

I see. Thank you.



> I'm also working on this issue :)

Ah, okay. Seems I'm late ^^

**Comment by missnadia** [comment]
#5
