### ISSUE TITLE
Migrate project to TypeScript

### ISSUE THREAD

**Issue by Jeconias** [Jeconias/calendarjs#33]
The project will be migrated to TypeScript.

**Reasons:**
- Facilitate the development and implementation of new features,
- Ensure parameter understanding.

#### Progress
- [x] Render calendar and navigation in arrows (left, right);
- [x] Change Language;
- [ ] Change Theme;
- [ ] Container to show all events in date determinate;
- [ ] Container to show Settings;

All these features exist in the version without TypeScript.

**Comment by leventdeniz** [comment]
The code should also be split up in different files for easier development. Webpack will merge them together as one calendar.min.js again

**Comment by Jeconias** [comment]
> The code should also be split up in different files for easier development. Webpack will merge them together as one calendar.min.js again

Yes, it will be done.
